### ISSUE TITLE
Random Background color

### ISSUE THREAD

**Issue by AlaaMarawi** [lrferreiro/flutter_initicon#3]
Hi, is there any way to add random option for background color ? 
generating totally random colors causes some results with white text on a white background for example, or many ugly variable colors that does not fit white text. same with 3rd party packages.
flutter_profile_picture package does this by the way but it is only for circular avatar..

Thank you

**Comment by stact** [comment]
Hi I'm using Theme Data to determine the darkness of a color, and it will decide about the text color (black or white).

You can create a simple method, or use Color extension

```dart
Color getTextColor(Color backgroundColor) {
    // Light or Dark mode 
    final isLight = Theme.of(context).brightness == Brightness.light;
    
    // Check the darkness of the background
    final isLightBackground = ThemeData.estimateBrightnessForColor(backgroundColor) == Brightness.light;
    // Depends on Light or Dark mode, returns the textColor 
    final textColor = isLight
        ? (isLightBackground || backgroundColor.opacity < 0.5)
            ? Colors.black
            : Colors.white
        : (!isLightBackground || backgroundColor.opacity < 0.5)
            ? Colors.white
            : Colors.black;

    return textColor;
  }
```

**Comment by lrferreiro** [comment]
The background color is optional and now depends on the input text or override it.
